# Render deployment configuration
services:
  # Web Service
  - type: web
    name: redis-clone-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: redis-clone-db
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: redis-clone-db
          property: port
      - key: REDIS_PASSWORD
        generateValue: true

  # Redis Database
  - type: redis
    name: redis-clone-db
    ipAllowList: # Only allow connections from the web service
      - source: 0.0.0.0/0
        description: everywhere
    plan: free # Specify the plan (free, starter, etc.)